# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for ScreenshotOne MCP Server
FROM node:lts-alpine

# Create and set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production --ignore-scripts

# Copy source and tsconfig
COPY tsconfig.json ./
COPY src ./src

# Build the project
RUN npm install --ignore-scripts && npm run build

# Default command (can be overridden by Smithery)
CMD ["node", "build/index.js"]
